/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.mcp.core;

import io.ballerina.mcp.core.generator.GeneratorOptions;
import io.ballerina.mcp.core.generator.GeneratorUtils;
import io.ballerina.mcp.core.generator.McpProjectGenerator;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;
import java.util.stream.Stream;

/**
 * Integration tests for {@link McpProjectGenerator} using the petstore sample spec.
 */
public class McpProjectGeneratorTest {

    @Test
    public void testGeneratePetstoreProject() throws Exception {
        URL resource = getClass().getClassLoader().getResource("specs/petstore.yaml");
        Assert.assertNotNull(resource, "petstore.yaml test resource not found");

        Path inputPath = Paths.get(resource.toURI());
        Path outputPath = Files.createTempDirectory("mcp-gen-test-");

        GeneratorOptions options = new GeneratorOptions(inputPath, outputPath, "openapi");
        McpProjectGenerator generator = new McpProjectGenerator(options);
        generator.generate();

        Path projectDir = outputPath.resolve("petstore_mcp");

        // Verify all expected files are generated
        Assert.assertTrue(Files.exists(projectDir.resolve("main.bal")),
                "main.bal should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("types.bal")),
                "types.bal should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("Ballerina.toml")),
                "Ballerina.toml should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("README.md")),
                "README.md should be generated");

        // Verify main.bal content
        String mainBal = Files.readString(projectDir.resolve("main.bal"));
        assertContentEqualsResource(mainBal, "expected/petstore/main.bal");
        Assert.assertTrue(mainBal.contains("import ballerina/mcp;"), "Should import mcp");
        Assert.assertTrue(mainBal.contains("import ballerina/http;"), "Should import http");
        Assert.assertTrue(mainBal.contains("import ballerina/log;"), "Should import log");
        Assert.assertTrue(mainBal.contains("mcp:Listener mcpListener"), "Should declare mcp listener");
        Assert.assertTrue(mainBal.contains("@mcp:ServiceConfig"), "Should have service config");
        Assert.assertTrue(mainBal.contains("service mcp:Service"), "Should declare mcp service");
        Assert.assertTrue(mainBal.contains("remote function listPets"), "Should generate listPets function");
        Assert.assertTrue(mainBal.contains("remote function createPet"), "Should generate createPet function");
        Assert.assertTrue(mainBal.contains("remote function showPetById"), "Should generate showPetById function");
        Assert.assertTrue(mainBal.contains("remote function deletePet"), "Should generate deletePet function");
        Assert.assertTrue(mainBal.contains("@mcp:Tool"), "Should annotate functions with @mcp:Tool");
        Assert.assertTrue(mainBal.contains("https://petstore.example.com/v1"), "Should use correct base URL");

        // Verify types.bal — generated by TypeHandler from the raw OpenAPI model.
        // TypeHandler emits closed records; imports (constraint, http) are added only when needed.
        String typesBal = Files.readString(projectDir.resolve("types.bal"));
        assertContentEqualsResource(typesBal, "expected/petstore/types.bal");
        Assert.assertTrue(typesBal.contains("type Pet record {"), "Should generate Pet record");
        Assert.assertTrue(typesBal.contains("type NewPet record {"), "Should generate NewPet record");
        Assert.assertTrue(typesBal.contains("int id;"), "id should be required (no ?)");
        Assert.assertTrue(typesBal.contains("string name;"), "name should be required (no ?)");
        Assert.assertTrue(typesBal.contains("int age?;"), "age should be optional");

        // Verify Ballerina.toml content
        String toml = Files.readString(projectDir.resolve("Ballerina.toml"));
        Assert.assertTrue(toml.contains("[package]"), "Should have [package] section");
        Assert.assertTrue(toml.contains("name = \"petstore_mcp\""), "Should have correct package name");

        // Verify README.md content
        String readme = Files.readString(projectDir.resolve("README.md"));
        Assert.assertTrue(readme.contains("Petstore"), "README should mention API title");
        Assert.assertTrue(readme.contains("listPets"), "README should list tool functions");
    }

    @Test
    public void testGeneratedProjectCompiles() throws Exception {
        URL resource = getClass().getClassLoader().getResource("specs/petstore.yaml");
        Assert.assertNotNull(resource, "petstore.yaml test resource not found");

        Path inputPath = Paths.get(resource.toURI());
        Path outputPath = Files.createTempDirectory("mcp-compile-test-");

        new McpProjectGenerator(new GeneratorOptions(inputPath, outputPath, "openapi")).generate();

        Path projectDir = outputPath.resolve("petstore_mcp");

        ProcessBuilder pb = new ProcessBuilder(resolveBalExecutable(), "build");
        pb.directory(projectDir.toFile());
        pb.redirectErrorStream(true);

        Process process = pb.start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        int exitCode = process.waitFor();

        Assert.assertEquals(exitCode, 0,
                "Generated project should compile without errors. bal build output:\n" + output);
    }

    private String resolveBalExecutable() throws Exception {
        String ballerinaHome = System.getProperty("ballerina.home");
        Assert.assertNotNull(ballerinaHome,
                "System property 'ballerina.home' is not set for tests");

        String executableName = System.getProperty("os.name").toLowerCase().contains("windows")
                ? "bal.bat" : "bal";

        try (Stream<Path> paths = Files.walk(Paths.get(ballerinaHome))) {
            Path balPath = paths
                    .filter(p -> p.getFileName().toString().equals(executableName))
                    .filter(p -> p.getParent() != null && p.getParent().getFileName().toString().equals("bin"))
                    .findFirst()
                    .orElse(null);

            Assert.assertNotNull(balPath,
                    "Could not find '" + executableName + "' under ballerina.home: " + ballerinaHome);
            return balPath.toAbsolutePath().toString();
        }
    }

    @Test
    public void testDerivePackageName() {
        Assert.assertEquals(GeneratorUtils.derivePackageName("Petstore"), "petstore_mcp");
        Assert.assertEquals(GeneratorUtils.derivePackageName("My REST API"), "my_rest_api_mcp");
        Assert.assertEquals(GeneratorUtils.derivePackageName(""), "mcp_server");
        Assert.assertEquals(GeneratorUtils.derivePackageName(null), "mcp_server");
        Assert.assertEquals(GeneratorUtils.derivePackageName("123 API"), "_123_api_mcp");
    }

    @Test
    public void testGenerateProjectWithoutSchemasDoesNotCreateTypesFile() throws Exception {
                URL resource = getClass().getClassLoader().getResource("specs/no-schemas.yaml");
                Assert.assertNotNull(resource, "no-schemas.yaml test resource not found");

                Path inputPath = Paths.get(resource.toURI());
                Path outputPath = Files.createTempDirectory("mcp-no-schema-test-");

                new McpProjectGenerator(new GeneratorOptions(inputPath, outputPath, "openapi")).generate();

                Path projectDir = outputPath.resolve("minimal_api_mcp");

                Assert.assertTrue(Files.exists(projectDir.resolve("main.bal")), "main.bal should be generated");
                Assert.assertTrue(Files.exists(projectDir.resolve("Ballerina.toml")), "Ballerina.toml should be generated");
                Assert.assertTrue(Files.exists(projectDir.resolve("README.md")), "README.md should be generated");
                Assert.assertFalse(Files.exists(projectDir.resolve("types.bal")),
                                "types.bal should not be generated when no schemas exist");

                String mainBal = Files.readString(projectDir.resolve("main.bal"));
                assertContentEqualsResource(mainBal, "expected/minimal-api/main.bal");
        }

        private void assertContentEqualsResource(String actualContent, String resourcePath) {
                URL resource = getClass().getClassLoader().getResource(resourcePath);
                Assert.assertNotNull(resource, "Expected resource not found: " + resourcePath);

                try {
                        String expectedContent = Files.readString(Paths.get(Objects.requireNonNull(resource).toURI()));
                        Assert.assertEquals(normalize(actualContent), normalize(expectedContent),
                                        "Generated content does not match expected resource: " + resourcePath);
                } catch (Exception e) {
                        Assert.fail("Failed to read expected resource: " + resourcePath + ", " + e.getMessage(), e);
                }
        }

        private String normalize(String content) {
                return content.replace("\r\n", "\n").trim();
    }
}
