/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.mcp.core;

import io.ballerina.mcp.core.generator.GeneratorOptions;
import io.ballerina.mcp.core.generator.GeneratorUtils;
import io.ballerina.mcp.core.generator.McpProjectGenerator;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * Integration tests for {@link McpProjectGenerator} using the petstore sample spec.
 */
public class McpProjectGeneratorTest {

        @DataProvider(name = "petstoreSpecs")
        public Object[][] petstoreSpecs() {
                return new Object[][]{
                                {"specs/petstore.yaml"},
                                {"specs/petstore.json"}
                };
        }

        @Test(dataProvider = "petstoreSpecs")
        public void testGeneratePetstoreProject(String specResource) throws Exception {
                URL resource = getClass().getClassLoader().getResource(specResource);
                Assert.assertNotNull(resource, specResource + " test resource not found");

        Path inputPath = Paths.get(resource.toURI());
        Path outputPath = Files.createTempDirectory("mcp-gen-test-");

        GeneratorOptions options = new GeneratorOptions(inputPath, outputPath, "openapi");
        McpProjectGenerator generator = new McpProjectGenerator(options);
        generator.generate();

        Path projectDir = outputPath.resolve("petstore_mcp");

        // Verify all expected files are generated
        Assert.assertTrue(Files.exists(projectDir.resolve("main.bal")),
                "main.bal should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("types.bal")),
                "types.bal should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("Ballerina.toml")),
                "Ballerina.toml should be generated");
        Assert.assertTrue(Files.exists(projectDir.resolve("README.md")),
                "README.md should be generated");

        // Verify main.bal content
        String mainBal = Files.readString(projectDir.resolve("main.bal"));
        Assert.assertTrue(mainBal.contains("import ballerina/mcp;"), "Should import mcp");
        Assert.assertTrue(mainBal.contains("import ballerina/http;"), "Should import http");
        Assert.assertTrue(mainBal.contains("import ballerina/log;"), "Should import log");
        Assert.assertTrue(mainBal.contains("mcp:Listener mcpListener"), "Should declare mcp listener");
        Assert.assertTrue(mainBal.contains("@mcp:ServiceConfig"), "Should have service config");
        Assert.assertTrue(mainBal.contains("service mcp:Service"), "Should declare mcp service");
        Assert.assertTrue(mainBal.contains("remote function listPets"), "Should generate listPets function");
        Assert.assertTrue(mainBal.contains("remote function createPet"), "Should generate createPet function");
        Assert.assertTrue(mainBal.contains("remote function showPetById"), "Should generate showPetById function");
        Assert.assertTrue(mainBal.contains("remote function deletePet"), "Should generate deletePet function");
        Assert.assertTrue(mainBal.contains("@mcp:Tool"), "Should annotate functions with @mcp:Tool");
        Assert.assertTrue(mainBal.contains("https://petstore.example.com/v1"), "Should use correct base URL");

        // Verify types.bal — generated by TypeHandler from the raw OpenAPI model.
        // TypeHandler emits closed records; imports (constraint, http) are added only when needed.
        String typesBal = Files.readString(projectDir.resolve("types.bal"));
        Assert.assertTrue(typesBal.contains("type Pet record {"), "Should generate Pet record");
        Assert.assertTrue(typesBal.contains("type NewPet record {"), "Should generate NewPet record");
        Assert.assertTrue(typesBal.contains("int id;"), "id should be required (no ?)");
        Assert.assertTrue(typesBal.contains("string name;"), "name should be required (no ?)");
        Assert.assertTrue(typesBal.contains("int age?;"), "age should be optional");

        // Verify Ballerina.toml content
        String toml = Files.readString(projectDir.resolve("Ballerina.toml"));
        Assert.assertTrue(toml.contains("[package]"), "Should have [package] section");
        Assert.assertTrue(toml.contains("name = \"petstore_mcp\""), "Should have correct package name");

        // Verify README.md content
        String readme = Files.readString(projectDir.resolve("README.md"));
        Assert.assertTrue(readme.contains("Petstore"), "README should mention API title");
        Assert.assertTrue(readme.contains("listPets"), "README should list tool functions");
    }

        @DataProvider(name = "goldenMainSpecs")
        public Object[][] goldenMainSpecs() {
                return new Object[][]{
                                {"specs/no-operation-id.yaml", "expected/no-operation-id/main.bal"},
                                {"specs/multi-query-param.yaml", "expected/multi-query-param/main.bal"},
                                {"specs/ref-query-parameters.yaml", "expected/ref-query-parameters/main.bal"}
                };
        }

        @Test(dataProvider = "goldenMainSpecs")
        public void testGeneratedMainMatchesExpectedForSelectedFixtures(String specResource,
                                                                                                                                         String expectedMainResource)
                        throws Exception {
                URL resource = getClass().getClassLoader().getResource(specResource);
                Assert.assertNotNull(resource, specResource + " test resource not found");

                Path inputPath = Paths.get(resource.toURI());
                Path outputPath = Files.createTempDirectory("mcp-golden-test-");

                new McpProjectGenerator(new GeneratorOptions(inputPath, outputPath, "openapi")).generate();

                Path projectDir = findGeneratedProjectDir(outputPath);
                String generatedMain = Files.readString(projectDir.resolve("main.bal"));
                assertContentEqualsResource(generatedMain, expectedMainResource);
        }

    @Test
    public void testGeneratedProjectCompiles() throws Exception {
        URL resource = getClass().getClassLoader().getResource("specs/petstore.yaml");
        Assert.assertNotNull(resource, "petstore.yaml test resource not found");

        Path inputPath = Paths.get(resource.toURI());
        Path outputPath = Files.createTempDirectory("mcp-compile-test-");

        new McpProjectGenerator(new GeneratorOptions(inputPath, outputPath, "openapi")).generate();

        Path projectDir = outputPath.resolve("petstore_mcp");
        String ballerinaHome = System.getProperty("ballerina.home");
        Assert.assertNotNull(ballerinaHome, "ballerina.home system property should be set for tests");

        Path balExecutable = findBalExecutable(Paths.get(ballerinaHome));
        Assert.assertNotNull(balExecutable, "Ballerina executable should exist under ballerina.home");

        ProcessBuilder pb = new ProcessBuilder(buildBalBuildCommand(balExecutable));
        pb.directory(projectDir.toFile());
        pb.redirectErrorStream(true);

        Process process = pb.start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        int exitCode = process.waitFor();

        Assert.assertEquals(exitCode, 0,
                "Generated project should compile without errors. bal build output:\n" + output);
    }

    @Test
    public void testDerivePackageName() {
        Assert.assertEquals(GeneratorUtils.derivePackageName("Petstore"), "petstore_mcp");
        Assert.assertEquals(GeneratorUtils.derivePackageName("My REST API"), "my_rest_api_mcp");
        Assert.assertEquals(GeneratorUtils.derivePackageName(""), "mcp_server");
        Assert.assertEquals(GeneratorUtils.derivePackageName(null), "mcp_server");
        Assert.assertEquals(GeneratorUtils.derivePackageName("123 API"), "_123_api_mcp");
    }

        private Path findBalExecutable(Path ballerinaHome) throws Exception {
                String os = System.getProperty("os.name").toLowerCase();
                String preferred = os.contains("win") ? "bal.bat" : "bal";
                String fallback = os.contains("win") ? "bal" : "bal.bat";

                try (Stream<Path> pathStream = Files.walk(ballerinaHome)) {
                        Path preferredPath = pathStream
                                        .filter(Files::isRegularFile)
                                        .filter(path -> {
                                                String fileName = path.getFileName().toString();
                                                return fileName.equals(preferred);
                                        })
                                        .filter(path -> path.getParent() != null
                                                        && path.getParent().getFileName() != null
                                                        && path.getParent().getFileName().toString().equals("bin"))
                                        .findFirst()
                                        .orElse(null);

                        if (preferredPath != null) {
                                return preferredPath;
                        }
                }

                try (Stream<Path> pathStream = Files.walk(ballerinaHome)) {
                        return pathStream
                                        .filter(Files::isRegularFile)
                                        .filter(path -> {
                                                String fileName = path.getFileName().toString();
                                                return fileName.equals(fallback);
                                        })
                                        .filter(path -> path.getParent() != null
                                                        && path.getParent().getFileName() != null
                                                        && path.getParent().getFileName().toString().equals("bin"))
                                        .findFirst()
                                        .orElse(null);
                }
        }

        private Path findGeneratedProjectDir(Path outputPath) throws Exception {
                try (Stream<Path> pathStream = Files.list(outputPath)) {
                        Path projectDir = pathStream
                                        .filter(Files::isDirectory)
                                        .findFirst()
                                        .orElse(null);
                        Assert.assertNotNull(projectDir, "Generated project directory not found");
                        return projectDir;
                }
        }

        private void assertContentEqualsResource(String actualContent, String resourcePath) throws Exception {
                URL resource = getClass().getClassLoader().getResource(resourcePath);
                Assert.assertNotNull(resource, "Expected resource not found: " + resourcePath);

                String expectedContent = Files.readString(Paths.get(resource.toURI()));
                Assert.assertEquals(normalize(actualContent), normalize(expectedContent),
                                "Generated content does not match expected resource: " + resourcePath);
        }

        private String normalize(String content) {
                return content.replace("\r\n", "\n").trim();
        }

        private List<String> buildBalBuildCommand(Path balExecutable) throws Exception {
                String os = System.getProperty("os.name").toLowerCase();
                List<String> command = new ArrayList<>();

                if (os.contains("win")) {
                        command.add(balExecutable.toString());
                        command.add("build");
                        return command;
                }

                if (Files.isExecutable(balExecutable)) {
                        command.add(balExecutable.toString());
                        command.add("build");
                        return command;
                }

                command.add("sh");
                command.add(balExecutable.toString());
                command.add("build");
                return command;
        }
}
